// <auto-generated />
using System;
using LoanManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoanManagementSystem.Data.Migrations
{
    [DbContext(typeof(LMSContext))]
    partial class LMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Latin1_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LoanManagementSystem.Models.BankDetail", b =>
                {
                    b.Property<string>("BankName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BankAddress")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("BankName")
                        .HasName("PK_Bank");

                    b.ToTable("BankDetails");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.CustomerInfo", b =>
                {
                    b.Property<int>("Custid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustAddress")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Custname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Pan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("PAN");

                    b.Property<string>("Phoneno")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Custid")
                        .HasName("PK__Customer__049D3E81E80459D9");

                    b.ToTable("CustomerInfo");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.Emi", b =>
                {
                    b.Property<int>("Emiid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EMIId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Amount")
                        .IsRequired()
                        .HasColumnType("decimal(18,0)");

                    b.Property<int?>("Custid")
                        .HasColumnType("int");

                    b.Property<string>("LoanType")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Emiid");

                    b.HasIndex("Custid");

                    b.ToTable("EMI");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.Emipayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Emiamount")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("EMIAmount");

                    b.Property<int?>("Emiid")
                        .HasColumnType("int")
                        .HasColumnName("EMIId");

                    b.Property<decimal?>("Fine")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("LastPaid")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime?>("ReceiptDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("Emiid");

                    b.ToTable("EMIPayments");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.LoanApplication", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Custid")
                        .HasColumnType("int");

                    b.Property<string>("LoanType")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("AppId")
                        .HasName("PK__LoanAppl__8E2CF7F935191B9F");

                    b.HasIndex("Custid");

                    b.ToTable("LoanApplication");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.LoanType", b =>
                {
                    b.Property<string>("LoanType1")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("LoanType");

                    b.Property<string>("InterestRate")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("LoanType1")
                        .HasName("PK__LoanType__3C62B94646D5B118");

                    b.ToTable("LoanType");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.Emi", b =>
                {
                    b.HasOne("LoanManagementSystem.Models.CustomerInfo", "Cust")
                        .WithMany("Emis")
                        .HasForeignKey("Custid")
                        .HasConstraintName("FK__EMI__Custid__2B3F6F97");

                    b.Navigation("Cust");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.Emipayment", b =>
                {
                    b.HasOne("LoanManagementSystem.Models.Emi", "Emi")
                        .WithMany("Emipayments")
                        .HasForeignKey("Emiid")
                        .HasConstraintName("FK__EMIPaymen__EMIId__2E1BDC42");

                    b.Navigation("Emi");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.LoanApplication", b =>
                {
                    b.HasOne("LoanManagementSystem.Models.CustomerInfo", "Cust")
                        .WithMany("LoanApplications")
                        .HasForeignKey("Custid")
                        .HasConstraintName("FK__LoanAppli__Custi__286302EC");

                    b.Navigation("Cust");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.CustomerInfo", b =>
                {
                    b.Navigation("Emis");

                    b.Navigation("LoanApplications");
                });

            modelBuilder.Entity("LoanManagementSystem.Models.Emi", b =>
                {
                    b.Navigation("Emipayments");
                });
#pragma warning restore 612, 618
        }
    }
}
